apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-tap-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-tap-demo
spec:
  source:
    git:
      url: https://github.com/TYsewyn/spring-petclinic-tap-demo.git
      ref:
        branch: main
